DecompositionTree: DecompositionTree.cpp
	g++ -std=c++11 -o DecompositionTree DecompositionTree.cpp ./lib/dNode.cpp ./lib/dTree.cpp ./lib/graph.cpp ./lib/utils.cpp

RandomTree: RandomTree.cpp
	g++ -std=c++11 -o RandomTree RandomTree.cpp
